### ISSUE TITLE
The encoder value from the right MTM's 7th axis is not continuous.

### ISSUE THREAD

**Issue by mohismtaoism** [jhu-cisst/mechatronics-software#10]
After updating to the version 6 of FPGA, we found that the encoder value from the right MTM's 7th axis is not continuous very badly, it usually lost some values when we rotate the axis by hand. This axis is attached to the port 2 (0---3)from the board 3(0---3).  Therefore we went back to the version 5 of FPGA, the scenario is better, but the problem is still existing. Do you meet with the problem like that? Should I file an issue under mechatronics-firmware?

**Comment by pkazanzides** [comment]
This seems like a hardware problem (maybe connector or wiring) rather than a firmware problem.  If you switch the controller boxes, does the problem change to the left MTM?  If yes, then there is a problem with your right controller box (for example, a loose connector inside the box).  If no, then there is a problem with your right MTM.

**Comment by ming1259** [comment]
I  can not follow your problem ,  so I  should  learn  more knowledge about  mechatronics
