### ISSUE TITLE
The proximity check is disfunctional in version 6 of FPGA

### ISSUE THREAD

**Issue by mohismtaoism** [jhu-cisst/mechatronics-software#9]
Inside the issue #8 , @pkazanzides suggested me to use the version 6 of FPGA to get better velocity data. But after some tests on the version 6, I found a new problem. 

The davincci MTM has the function to test whether the doctor approaches the MTM. And we use the following interfaces to check:

    AmpIO_UInt8 GetDigitalOutput(void) const;
    AmpIO_UInt8 GetNegativeLimitSwitches(void) const;
    AmpIO_UInt8 GetPositiveLimitSwitches(void) const;
    AmpIO_UInt8 GetHomeSwitches(void) const; 

Mapping these interfaces to the result of qladisp command:

     Status: 0x40200000   Timestamp: 00008154  DigOut: 0xD
     NegLim: 0xE          PosLim: 0xE          Home: 0xE
     EncA: 0x2            EncB: 0x3            EncInd: 0xE

The middle row's three data were used by our to check whether the head of the doctor approaches the MTM,  it worked well in version 5, but it can't work in version 6. The phenomenon is that these three data never change when I cover the checking area:

    NegLim: 0xE          PosLim: 0xE          Home: 0xE

Therefore we can't use the version 6 due to this dysfunction, please help me fix it.

**Comment by pkazanzides** [comment]
I am sorry you are experiencing this problem. The Rev 6 firmware was released almost two years ago and no similar problems have been reported, but let us see if we can figure this out.

Based on the qladisp status feedback, the firmware is detecting your QLA as being prior to Rev 1.4. Is that correct (i.e., what version is shown on the board silkscreen)?

You mention the dVRK head sensor. From your description, I think you are using the sensors that are in the master console of a full system (i.e., the last option documented here:  https://github.com/jhu-dvrk/sawIntuitiveResearchKit/wiki/HeadSensor). Is that correct? If so, we have the same setup at JHU and have been running the Rev 6 firmware without a problem.

What software are you using? Clearly, you are using the low-level interface (mechatronics-software) and utility programs such as qladisp.  Make sure you have the latest versions of those. Also, if you are using the standard dVRK software, please let me know which version.  The latest release is 1.7.1.

**Comment by mohismtaoism** [comment]
> Based on the qladisp status feedback, the firmware is detecting your QLA as being prior to Rev 1.4. Is that correct (i.e., what version is shown on the board silkscreen)?

I am sorry, I can't confirm the version of QLA. You can tell me more details. But I think it's fulfill the requirements.

>You mention the dVRK head sensor. From your description, I think you are using the sensors that are in the master console of a full system (i.e., the last option documented here: https://github.com/jhu-dvrk/sawIntuitiveResearchKit/wiki/HeadSensor). Is that correct? If so, we have the same setup at JHU and have been running the Rev 6 firmware without a problem.

The head sensor is the same as [davinci-head-sensor](https://github.com/jhu-dvrk/sawIntuitiveResearchKit/wiki/HeadSensor#davinci-head-sensor). It has four light sensors.

>What software are you using? Clearly, you are using the low-level interface (mechatronics-software) and utility programs such as qladisp. Make sure you have the latest versions of those. Also, if you are using the standard dVRK software, please let me know which version. The latest release is 1.7.1.

We are only using the low-level interface (mechatronics-software) and utility programs such as qladisp. And our current version is 1.4.1. We have not used the  standard dVRK software, and what advantages are they provide?

Therefore I think I should update the mechatronics-software firstly, and check the head sensor feature. Thanks very much for your quick respond.

**Comment by pkazanzides** [comment]
To check the version of the QLA, you could open the controller box. Alternatively, you can check which build (hardware batch) you were part of here: https://github.com/jhu-dvrk/sawIntuitiveResearchKit/wiki/Timeline, then check which QLA version was used for that build here:  https://github.com/jhu-cisst/QLA#release-notes.

As far as I can tell from the mechatronics-software CHANGELOG, there was no Version 1.4.1 -- there was a Version 1.4.0.  That should be sufficient.  But, if your version is older than 1.4.0, you should definitely update.

The advantage of using all the dVRK software is that your system would work similar to a real da Vinci, without you having to write all the code.

**Comment by mohismtaoism** [comment]
>As far as I can tell from the mechatronics-software CHANGELOG, there was no Version 1.4.1 -- there was a Version 1.4.0. That should be sufficient. But, if your version is older than 1.4.0, you should definitely update.

Yes, our original version of mechatronics-software is 1.4.0, and I have updated to 1.5.0. But the head sensor seems still don't work.

>Alternatively, you can check which build (hardware batch) you were part of here: https://github.com/jhu-dvrk/sawIntuitiveResearchKit/wiki/Timeline, then check which QLA version was used for that build here: https://github.com/jhu-cisst/QLA#release-notes.

I found my company is on the list of [timeline](https://github.com/jhu-dvrk/sawIntuitiveResearchKit/wiki/Timeline), it's in the end of the list, and it's called Surgnova. I think our QLA version is 1.4b

**Comment by pkazanzides** [comment]
If you have QLA Version 1.4+, then there is a problem.  Above, you indicated that `qladisp` showed the status register as 0x40200000. The meaning of the bits is defined here:  https://github.com/jhu-cisst/mechatronics-software/wiki/InterfaceSpec#41-status-read.  The first nibble (4 bits) should always be 4. The second should match the rotary switch setting on the FPGA board.  But the lowest two bits of the third nibble indicate the digital output configuration, which is autodetected by the firmware. For QLA Version 1.4+, this should be `11`. For older versions it will be `10`.  For QLA 1.4+, the digital output lines are actually bidirectional, so it is necessary for the firmware to set the direction to output (the default power up state is input). Since the firmware did not correctly detect the QLA version, your output lines are not working and therefore the head sensor will not work (one output line is used to turn on the LEDs). Note that you can still toggle the DOUT value using `qladisp` and the output will appear to change (as far as the firmware is concerned, it is changing), but the hardware driver will not be driving the physical line.

The firmware check of the QLA version was introduced in firmware Rev 5 and was not changed in firmware Rev 6, so I am not sure why you only saw this problem with Rev 6.  Can you check the status of the other boards?  Since you have controllers for 2 MTMs, you should have board ids 0, 1, 2 and 3.  Note that it is not worth trying any firmware before Rev 5 because it will not support the digital outputs of QLA 1.4+.

Also, even though your system only has 2 MTMs, I think the higher-level dVRK software would still be useful for you, especially if you are planning to use ROS.  The dVRK software will do the joint-level control, Cartesian control, gravity compensation, provide hooks for Cartesian impedance control, etc., and you can interface via ROS topics. If you would like to try this, @adeguet1 would be the best person to help.

**Comment by mohismtaoism** [comment]
# About the status register

* Board 0:  Status: 0x40200000
* Board 1:  Status: 0x41300000
* Board 2:  Status: 0x42300000
* Board 3:  Status: 0x43300000

According to your last comment, my board 0 is old version, and other 3 boards are new version. Can we make this statement?  If the board 0 is the old version, how can we update?  And can we just wire the head sensor to the other boards to fix the problem?

# About the higher level software

At present  our software is based on mechatronics-software right now, moving to the higher level library is not very easy, it needs more works. But we can start tests on the higher level software after tackle the head checking and velocity issue.

**Comment by pkazanzides** [comment]
I highly doubt that board #0 is the old version. More likely, there is something wrong with the board that is causing the auto-detect to fail. You can check the QLA serial number to be sure.  You just have to run `pgm1394` and select option 7. These boards are all unit tested after assembly and the testing would have caught that problem, so it must have happened later.

You can certainly connect the head sensor to another controller box, or swap controller boxes (changing rotary switch settings to be consistent with the standard numbering convention).

**Comment by mohismtaoism** [comment]
The pgm1394 output for board 0 is below:

sm@PSM1:~/alexander/product/bin/firmware/v6$ sudo pgm1394 0
Started pgm1394, using AmpIO version 1.5.0
FirewirePort::Init: number of ports = 1
FirewirePort::Init: successfully initialized port 0
FirewirePort::Init: successfully disabled cycle start packet
FirewirePort::ScanNodes: base node id = ffc0
FirewirePort::ScanNodes: building node map for 5 nodes:
  Node 0, BoardId = 3, Firmware Version = 6
  Node 1, BoardId = 2, Firmware Version = 6
  Node 2, BoardId = 1, Firmware Version = 6
  Node 3, BoardId = 0, Firmware Version = 6
FirewirePort::ScanNodes: all nodes broadcast capable and support shorter wait

Board: 0
MCS file: FPGA1394Eth-QLA.mcs
PROM Id: 202015

0) Exit programmer
1) Program PROM
2) Verify PROM
3) Read PROM data
4) Program FPGA SN
5) Program QLA SN
6) Read FPGA SN
7) Read QLA SN

Select option: 7
QLA serial number: 6006-67

Board: 0
MCS file: FPGA1394Eth-QLA.mcs
PROM Id: 202015

0) Exit programmer
1) Program PROM
2) Verify PROM
3) Read PROM data
4) Program FPGA SN
5) Program QLA SN
6) Read FPGA SN
7) Read QLA SN

Select option:

**Comment by mohismtaoism** [comment]
Board 0:  QLA serial number: 6006-67
Board 1:  QLA serial number: 6006-60
Board 2:  QLA serial number: 6006-80
Board 3:  QLA serial number: 6006-54

**Comment by pkazanzides** [comment]
These boards were all produced in the latest build and therefore are all Version 1.4b.  For some reason, the autodetect firmware is failing to correctly detect Board #0.  The autodetection works by checking the state of the two direction-control lines. On the old QLA, these are not used and thus the signals float high (internal pullup resistors on FPGA). On QLA 1.4+, there are pull-down resistors to GND, so they should be low. The problem could be due to something simple, such as a problem with the resistors. The resistors used for the direction lines are part of a resistor pack that also affects the "motor voltage good" feedback and the "safety relay" feedback.

**Comment by mohismtaoism** [comment]
It seems not easy to tackle, isn't it?

Just now we connected the head sensor to another control box, it still didn't work. So strange!

**Comment by mohismtaoism** [comment]
Hi ! @pkazanzides After connecting to anther box and debugging, the head sensor works now, but the board 0 really has problems. So whatever, the problem solved! Thanks for your help!

**Comment by pkazanzides** [comment]
I am glad to hear that the head sensor is working, although clearly board #0 is not working correctly.  The digital outputs are not used for much on the dVRK, but other more important functions may be affected.  Presumably you have a spare board?

**Comment by mohismtaoism** [comment]
@pkazanzides  We have two DVRK boxes, four boards, the board 0 only fails at the head sensor, we only need to connect the sensor to another board, then change the related source codes, finally the sensor was working, Thanks for your explanation. This issue can be closed.
